### ISSUE TITLE
Result<T> monad - Error() versus Fail()

### ISSUE THREAD

**Issue by barangutan** [MonacsLib/Monacs#10]
This is a really neat library and I'm definitely going to start using it in my projects. My only minor gripe is:

I've seen some other implementations of a Result monad in C# with the states `Ok `and `Fail` (or Failure). I personally prefer `Fail` being the state for when (as you state in your docs) 

> you have a function and it may **fail** to execute properly

A function may fail on some criteria which I wouldn't technically regard as an error. For example:

 `public Result<User> RegisterUser(string email, string password)` 

may fail if a user with the same e-mail exists, however I wouldn't treat this as an "error" in my application.

**Comment by bartsokol** [comment]
I was considering different variants and finally decided that the `Ok`/`Error` combination is the way to go. The key argument was that F# uses this convention (as of 4.1), which makes the switch between the languages a bit easier. I was also looking at the other languages and platforms (like Rust, Elixir or Elm) and I found that it's the most popular one there as well (`Ok`/`Error` or `Err`). I think it makes sense to keep it as it is now.

I'm thinking about adding two other (yet similar) monads that can help with the cases where there is no error, but the operation may end up on one of two different tracks. One is `Either` monad (`Choice` in F#) with `Left` and `Right` tracks (`Choice1of2` and `Choice2of2` in F#), the other is `ValidationResult` with `Passed` and `Failed` tracks (naming not decided, will create an issue to discuss it).

Not sure if it will help with your concerns, but I hope that at least it makes the decisions I've made a bit more understandable :)

**Comment by pizycki** [comment]
I would stick to `Error` too. Basicly, because its more common in other FP languages.

I like the idea of introducing `Either` monad. Definitely needed!

**Comment by barangutan** [comment]
@bartsokol I appreciate the reply. I'm not familiar with F# or any other FP languages for that matter so I do understand why you would want to stick to conventions. I think the `Either` monad could definitely help me in a lot of ways.

**Comment by bartsokol** [comment]
I think in upcoming week or two I will start working on `Either`, just need to finish with documenting what is there already to not get too much behind ;)

**Comment by barangutan** [comment]
I understand. As of now I really don't understand the `ErrorDetail` class. I'm sure I will understand better when the documentation is complete but for now I see no way of returning an Result.Error with just a simple error message.

**Comment by bartsokol** [comment]
I'll update the docs soon, so far I can give you a hint that it's possible to use the default value for other parameters if you don't need to specify them. The only thing that is needed is the level of the error. The easiest way to do it is to use factory methods from the `Errors` class, like `Errors.Warn()`.
