### ISSUE TITLE
Unit type factory method shall be called "Create" instead of "Default"

### ISSUE THREAD

**Issue by pizycki** [MonacsLib/Monacs#11]
As in the title.

Reasoning behind this is as "Default" can imply that there are *other* values available for Unit type, which makes no sense.

My proposition is to rename this factory method to `Create`. 

`Unit.Value` (taken from [MediatR library](https://github.com/jbogard/MediatR/blob/8100035db238ba116a20ccd5e10538aaf37e5f65/src/MediatR/Unit.cs)) makes no sense either.

**Comment by bartsokol** [comment]
`Unit` type has only one value, which is its default value (`default(Unit)`). It's a convention also found in [Reactive Extensions](https://github.com/Reactive-Extensions/Rx.NET/blob/develop/Rx.NET/Source/src/System.Reactive/Unit.cs) from where this type is adopted. `Create` doesn't make sense IMHO, as nothing is created. `Value` makes some sense, but I'm fine with `Default as well.

**Comment by pizycki** [comment]
I still don't like  `Default` property for `Unit` type. I think it's misleading.

I've done some reading about `Unit` type in other languages (starting from Haskell).
https://en.wikipedia.org/wiki/Unit_type
https://stackoverflow.com/questions/16892570/what-is-in-haskell-exactly
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/unit-type

The statement that "Unit has only one value" repeats over some places in the Internet and I guess it's the most appropriate.

It looks to me like `Unit.Default` specifies **how** `unit` instance will be created - by `default(Unit)`.
And yeah, there is something created after all :P
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/default

Another thing is that if somebody would like to use both [Monacs](https://github.com/MonacsLib/Monacs) and [Reactive Extension](https://github.com/Reactive-Extensions/Rx.NET), he will eventualy notice very similiar types in both libraries. 
As long as appropriate `using` statements will be included this doesn't seem to be an issue. Yet it might get bit frustrating once calling for help IDE after typing `Unit.Default` and getting reference to two different libraries.
Providing different names for `Unit` factories in different libraries would be beneficial for users.

**So right now, I'd change `Unit.Defualt` to `Unit.Value`.**

What do you think?

PS: Happy pizza day!! 🍕 🍕 🍕

**Comment by bartsokol** [comment]
`Value` makes some sense, but from the other side, it doesn't contain any value ;) Will think if it's a good choice over the weekend :)

P.S. Enjoy your 🍕 ! :)

**Comment by bartsokol** [comment]
With recent changes that included a change to readonly structs and using references to the default value, the name *Default* seems to be more appropriate. Will close this issue as it's more of a preference than any practical difference at this point.
