### ISSUE TITLE
Add XML docs to enhance discoverability in IDEs 

### ISSUE THREAD

**Issue by bartsokol** [MonacsLib/Monacs#4]
Add XML docs to extensions, so that one can see what does given function do without the need to dig into docs. From the other side, XML docs can also be used do generate docs for the library's API.

**Comment by pizycki** [comment]
I'll have a look at it.

**Comment by pizycki** [comment]
Just started working on it.
Here is the first commit with documentation for `Result` structure https://github.com/pizycki/Monacs/commit/a2df319fb624332cc5c950b50661b91ff77efa26

I assumed that Result can become Success or Failure and that way I'd like to continue commenting the code. If you have any thoughts on this, please share.

The english might not be perfect, so if something doesn't sounds good and should be rewritten, point it out as well.

**Comment by bartsokol** [comment]
Good start 👍 I will add some comments to the commit, feel free to reply and point out good and bad ideas ;)

As for the ways to call the paths, I'm thinking of using the track naming, like "Result is on success track" or "Result is on error track" to indicate the path. Thoughts?

And don't worry about the language at this point, we can do final review once all is done and improve it if there will be such need :)

**Comment by pizycki** [comment]
Cool, i'll continue working:)

**Comment by bartsokol** [comment]
I've added some sample docs in [this PR](https://github.com/MonacsLib/Monacs/pull/8), feel free to comment there as well and use it as an example.

**Comment by pizycki** [comment]
Just updated `Result` doc in this commit https://github.com/pizycki/Monacs/commit/af1c9eaf6750b91d6c13059ef847931624bef22b

**Comment by pizycki** [comment]
Updates in-code doc for [Unit](https://github.com/pizycki/Monacs/commit/3d3167adae0476fa4e888c67e1e8b70d6aa70464) and [Option](https://github.com/pizycki/Monacs/commit/652f687707a73f2758ef665bd07547f88d2c7e97).
I didn't want to document ErrorDetails as I'm not sure how it's supposed to work. I think I'll need some examples for this.

**Comment by bartsokol** [comment]
I've recently created [`develop` branch](https://github.com/MonacsLib/Monacs/tree/develop) where I will be merging changes in preparation for release. Please rebase your branch on it, there are some new docs merged there as well.

If you won't be sure what to put in the docs for some type or method you can leave it to me or put TODO in comments and we can work on it together when the PR will be created.

**Comment by bartsokol** [comment]
Documentation added in version 0.2.0 :)
