### ISSUE TITLE
The value of Result with error is default(T)

### ISSUE THREAD

**Issue by pizycki** [MonacsLib/Monacs#6]
When I get `Error` (which is `Result` with `Result.IsError = true`) I'd like the `Value` property to behave differently, for example by throwing `InvalidOperatoException`.

Say, I want to count active users in my system. I'd write a query which would return me `Result<int>` (this is not primitive obssesion, right?). Once I have my result, I can call `result.Value` on it which would return me a `0` value, wether its status is ok or not.

We should keep in mind that this library will be used by guys who come from OOP world and are not used for technices like pattern matching or ROP.

**Comment by bartsokol** [comment]
Unfortunately, there is no way to prevent users from accessing `Value` in C# and I'm not a fan of throwing any exceptions in the code. Usage of Value should be very limited, mostly to the case when you're writing some extension. I would suggest in documentation/comments to use `Bind`, `Map`, `Match` or `GetOrDefault`, whatever is more applicable in given case. It isn't perfect either, but at least we avoid throwing and having additional conditionals in the code.

**Comment by pizycki** [comment]
I'm not a fan neither, but it makes sense in this case. It kind of forces programmer to use matching. I guess we should do such things to discourage programmers to do things in *not safe* way.
I think rising exception is way better option here then leaving a room for hard to find bug.

**Comment by bartsokol** [comment]
Let's leave this issue open for some time and think a bit about it? I'm not convinced it's a good idea to throw an exception from `Value` and need some time to consider pros and cons.

**Comment by pizycki** [comment]
I'm working on xml doc of `Option` and just found out how F# `Option` deals with it. 
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/options#option-properties-and-methods
> Returns the underlying value, or throws a System.NullReferenceException if the value is None.

**Comment by bartsokol** [comment]
After some consideration, I decided to keep it as it is now, keeping it in line with (unwritten) no-throw policy in this library. I don't see much of a value in punishing the consumer for accessing the value in Error/None case - it should be more about good practices when things cannot be explicitly prevented. I will close this issue now.
